
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `entry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model entry
 * 
 */
export type entryModel = runtime.Types.Result.DefaultSelection<Prisma.$entryPayload>

export type AggregateEntry = {
  _count: EntryCountAggregateOutputType | null
  _avg: EntryAvgAggregateOutputType | null
  _sum: EntrySumAggregateOutputType | null
  _min: EntryMinAggregateOutputType | null
  _max: EntryMaxAggregateOutputType | null
}

export type EntryAvgAggregateOutputType = {
  id: number | null
}

export type EntrySumAggregateOutputType = {
  id: number | null
}

export type EntryMinAggregateOutputType = {
  id: number | null
  title: string | null
  content: string | null
  author: string | null
  image: string | null
}

export type EntryMaxAggregateOutputType = {
  id: number | null
  title: string | null
  content: string | null
  author: string | null
  image: string | null
}

export type EntryCountAggregateOutputType = {
  id: number
  title: number
  content: number
  author: number
  image: number
  _all: number
}


export type EntryAvgAggregateInputType = {
  id?: true
}

export type EntrySumAggregateInputType = {
  id?: true
}

export type EntryMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  author?: true
  image?: true
}

export type EntryMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  author?: true
  image?: true
}

export type EntryCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  author?: true
  image?: true
  _all?: true
}

export type EntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which entry to aggregate.
   */
  where?: Prisma.entryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entries to fetch.
   */
  orderBy?: Prisma.entryOrderByWithRelationInput | Prisma.entryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.entryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned entries
  **/
  _count?: true | EntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EntryMaxAggregateInputType
}

export type GetEntryAggregateType<T extends EntryAggregateArgs> = {
      [P in keyof T & keyof AggregateEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateEntry[P]>
}




export type entryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.entryWhereInput
  orderBy?: Prisma.entryOrderByWithAggregationInput | Prisma.entryOrderByWithAggregationInput[]
  by: Prisma.EntryScalarFieldEnum[] | Prisma.EntryScalarFieldEnum
  having?: Prisma.entryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EntryCountAggregateInputType | true
  _avg?: EntryAvgAggregateInputType
  _sum?: EntrySumAggregateInputType
  _min?: EntryMinAggregateInputType
  _max?: EntryMaxAggregateInputType
}

export type EntryGroupByOutputType = {
  id: number
  title: string
  content: string
  author: string
  image: string
  _count: EntryCountAggregateOutputType | null
  _avg: EntryAvgAggregateOutputType | null
  _sum: EntrySumAggregateOutputType | null
  _min: EntryMinAggregateOutputType | null
  _max: EntryMaxAggregateOutputType | null
}

type GetEntryGroupByPayload<T extends entryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EntryGroupByOutputType[P]>
      }
    >
  >



export type entryWhereInput = {
  AND?: Prisma.entryWhereInput | Prisma.entryWhereInput[]
  OR?: Prisma.entryWhereInput[]
  NOT?: Prisma.entryWhereInput | Prisma.entryWhereInput[]
  id?: Prisma.IntFilter<"entry"> | number
  title?: Prisma.StringFilter<"entry"> | string
  content?: Prisma.StringFilter<"entry"> | string
  author?: Prisma.StringFilter<"entry"> | string
  image?: Prisma.StringFilter<"entry"> | string
}

export type entryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  author?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type entryWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.entryWhereInput | Prisma.entryWhereInput[]
  OR?: Prisma.entryWhereInput[]
  NOT?: Prisma.entryWhereInput | Prisma.entryWhereInput[]
  title?: Prisma.StringFilter<"entry"> | string
  content?: Prisma.StringFilter<"entry"> | string
  author?: Prisma.StringFilter<"entry"> | string
  image?: Prisma.StringFilter<"entry"> | string
}, "id">

export type entryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  author?: Prisma.SortOrder
  image?: Prisma.SortOrder
  _count?: Prisma.entryCountOrderByAggregateInput
  _avg?: Prisma.entryAvgOrderByAggregateInput
  _max?: Prisma.entryMaxOrderByAggregateInput
  _min?: Prisma.entryMinOrderByAggregateInput
  _sum?: Prisma.entrySumOrderByAggregateInput
}

export type entryScalarWhereWithAggregatesInput = {
  AND?: Prisma.entryScalarWhereWithAggregatesInput | Prisma.entryScalarWhereWithAggregatesInput[]
  OR?: Prisma.entryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.entryScalarWhereWithAggregatesInput | Prisma.entryScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"entry"> | number
  title?: Prisma.StringWithAggregatesFilter<"entry"> | string
  content?: Prisma.StringWithAggregatesFilter<"entry"> | string
  author?: Prisma.StringWithAggregatesFilter<"entry"> | string
  image?: Prisma.StringWithAggregatesFilter<"entry"> | string
}

export type entryCreateInput = {
  title: string
  content: string
  author: string
  image: string
}

export type entryUncheckedCreateInput = {
  id?: number
  title: string
  content: string
  author: string
  image: string
}

export type entryUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
}

export type entryUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
}

export type entryCreateManyInput = {
  id?: number
  title: string
  content: string
  author: string
  image: string
}

export type entryUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
}

export type entryUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
}

export type entryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  author?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type entryAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type entryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  author?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type entryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  author?: Prisma.SortOrder
  image?: Prisma.SortOrder
}

export type entrySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type entrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  author?: boolean
  image?: boolean
}, ExtArgs["result"]["entry"]>

export type entrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  author?: boolean
  image?: boolean
}, ExtArgs["result"]["entry"]>

export type entrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  author?: boolean
  image?: boolean
}, ExtArgs["result"]["entry"]>

export type entrySelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  author?: boolean
  image?: boolean
}

export type entryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "author" | "image", ExtArgs["result"]["entry"]>

export type $entryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "entry"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    content: string
    author: string
    image: string
  }, ExtArgs["result"]["entry"]>
  composites: {}
}

export type entryGetPayload<S extends boolean | null | undefined | entryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$entryPayload, S>

export type entryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<entryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EntryCountAggregateInputType | true
  }

export interface entryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['entry'], meta: { name: 'entry' } }
  /**
   * Find zero or one Entry that matches the filter.
   * @param {entryFindUniqueArgs} args - Arguments to find a Entry
   * @example
   * // Get one Entry
   * const entry = await prisma.entry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends entryFindUniqueArgs>(args: Prisma.SelectSubset<T, entryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Entry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {entryFindUniqueOrThrowArgs} args - Arguments to find a Entry
   * @example
   * // Get one Entry
   * const entry = await prisma.entry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends entryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, entryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryFindFirstArgs} args - Arguments to find a Entry
   * @example
   * // Get one Entry
   * const entry = await prisma.entry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends entryFindFirstArgs>(args?: Prisma.SelectSubset<T, entryFindFirstArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryFindFirstOrThrowArgs} args - Arguments to find a Entry
   * @example
   * // Get one Entry
   * const entry = await prisma.entry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends entryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, entryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Entries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Entries
   * const entries = await prisma.entry.findMany()
   * 
   * // Get first 10 Entries
   * const entries = await prisma.entry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const entryWithIdOnly = await prisma.entry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends entryFindManyArgs>(args?: Prisma.SelectSubset<T, entryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Entry.
   * @param {entryCreateArgs} args - Arguments to create a Entry.
   * @example
   * // Create one Entry
   * const Entry = await prisma.entry.create({
   *   data: {
   *     // ... data to create a Entry
   *   }
   * })
   * 
   */
  create<T extends entryCreateArgs>(args: Prisma.SelectSubset<T, entryCreateArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Entries.
   * @param {entryCreateManyArgs} args - Arguments to create many Entries.
   * @example
   * // Create many Entries
   * const entry = await prisma.entry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends entryCreateManyArgs>(args?: Prisma.SelectSubset<T, entryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Entries and returns the data saved in the database.
   * @param {entryCreateManyAndReturnArgs} args - Arguments to create many Entries.
   * @example
   * // Create many Entries
   * const entry = await prisma.entry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Entries and only return the `id`
   * const entryWithIdOnly = await prisma.entry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends entryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, entryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Entry.
   * @param {entryDeleteArgs} args - Arguments to delete one Entry.
   * @example
   * // Delete one Entry
   * const Entry = await prisma.entry.delete({
   *   where: {
   *     // ... filter to delete one Entry
   *   }
   * })
   * 
   */
  delete<T extends entryDeleteArgs>(args: Prisma.SelectSubset<T, entryDeleteArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Entry.
   * @param {entryUpdateArgs} args - Arguments to update one Entry.
   * @example
   * // Update one Entry
   * const entry = await prisma.entry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends entryUpdateArgs>(args: Prisma.SelectSubset<T, entryUpdateArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Entries.
   * @param {entryDeleteManyArgs} args - Arguments to filter Entries to delete.
   * @example
   * // Delete a few Entries
   * const { count } = await prisma.entry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends entryDeleteManyArgs>(args?: Prisma.SelectSubset<T, entryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Entries
   * const entry = await prisma.entry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends entryUpdateManyArgs>(args: Prisma.SelectSubset<T, entryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entries and returns the data updated in the database.
   * @param {entryUpdateManyAndReturnArgs} args - Arguments to update many Entries.
   * @example
   * // Update many Entries
   * const entry = await prisma.entry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Entries and only return the `id`
   * const entryWithIdOnly = await prisma.entry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends entryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, entryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Entry.
   * @param {entryUpsertArgs} args - Arguments to update or create a Entry.
   * @example
   * // Update or create a Entry
   * const entry = await prisma.entry.upsert({
   *   create: {
   *     // ... data to create a Entry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Entry we want to update
   *   }
   * })
   */
  upsert<T extends entryUpsertArgs>(args: Prisma.SelectSubset<T, entryUpsertArgs<ExtArgs>>): Prisma.Prisma__entryClient<runtime.Types.Result.GetResult<Prisma.$entryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Entries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryCountArgs} args - Arguments to filter Entries to count.
   * @example
   * // Count the number of Entries
   * const count = await prisma.entry.count({
   *   where: {
   *     // ... the filter for the Entries we want to count
   *   }
   * })
  **/
  count<T extends entryCountArgs>(
    args?: Prisma.Subset<T, entryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Entry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EntryAggregateArgs>(args: Prisma.Subset<T, EntryAggregateArgs>): Prisma.PrismaPromise<GetEntryAggregateType<T>>

  /**
   * Group by Entry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends entryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: entryGroupByArgs['orderBy'] }
      : { orderBy?: entryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, entryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the entry model
 */
readonly fields: entryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for entry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__entryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the entry model
 */
export interface entryFieldRefs {
  readonly id: Prisma.FieldRef<"entry", 'Int'>
  readonly title: Prisma.FieldRef<"entry", 'String'>
  readonly content: Prisma.FieldRef<"entry", 'String'>
  readonly author: Prisma.FieldRef<"entry", 'String'>
  readonly image: Prisma.FieldRef<"entry", 'String'>
}
    

// Custom InputTypes
/**
 * entry findUnique
 */
export type entryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter, which entry to fetch.
   */
  where: Prisma.entryWhereUniqueInput
}

/**
 * entry findUniqueOrThrow
 */
export type entryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter, which entry to fetch.
   */
  where: Prisma.entryWhereUniqueInput
}

/**
 * entry findFirst
 */
export type entryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter, which entry to fetch.
   */
  where?: Prisma.entryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entries to fetch.
   */
  orderBy?: Prisma.entryOrderByWithRelationInput | Prisma.entryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for entries.
   */
  cursor?: Prisma.entryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of entries.
   */
  distinct?: Prisma.EntryScalarFieldEnum | Prisma.EntryScalarFieldEnum[]
}

/**
 * entry findFirstOrThrow
 */
export type entryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter, which entry to fetch.
   */
  where?: Prisma.entryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entries to fetch.
   */
  orderBy?: Prisma.entryOrderByWithRelationInput | Prisma.entryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for entries.
   */
  cursor?: Prisma.entryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of entries.
   */
  distinct?: Prisma.EntryScalarFieldEnum | Prisma.EntryScalarFieldEnum[]
}

/**
 * entry findMany
 */
export type entryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter, which entries to fetch.
   */
  where?: Prisma.entryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entries to fetch.
   */
  orderBy?: Prisma.entryOrderByWithRelationInput | Prisma.entryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing entries.
   */
  cursor?: Prisma.entryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entries.
   */
  skip?: number
  distinct?: Prisma.EntryScalarFieldEnum | Prisma.EntryScalarFieldEnum[]
}

/**
 * entry create
 */
export type entryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * The data needed to create a entry.
   */
  data: Prisma.XOR<Prisma.entryCreateInput, Prisma.entryUncheckedCreateInput>
}

/**
 * entry createMany
 */
export type entryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many entries.
   */
  data: Prisma.entryCreateManyInput | Prisma.entryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * entry createManyAndReturn
 */
export type entryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * The data used to create many entries.
   */
  data: Prisma.entryCreateManyInput | Prisma.entryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * entry update
 */
export type entryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * The data needed to update a entry.
   */
  data: Prisma.XOR<Prisma.entryUpdateInput, Prisma.entryUncheckedUpdateInput>
  /**
   * Choose, which entry to update.
   */
  where: Prisma.entryWhereUniqueInput
}

/**
 * entry updateMany
 */
export type entryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update entries.
   */
  data: Prisma.XOR<Prisma.entryUpdateManyMutationInput, Prisma.entryUncheckedUpdateManyInput>
  /**
   * Filter which entries to update
   */
  where?: Prisma.entryWhereInput
  /**
   * Limit how many entries to update.
   */
  limit?: number
}

/**
 * entry updateManyAndReturn
 */
export type entryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * The data used to update entries.
   */
  data: Prisma.XOR<Prisma.entryUpdateManyMutationInput, Prisma.entryUncheckedUpdateManyInput>
  /**
   * Filter which entries to update
   */
  where?: Prisma.entryWhereInput
  /**
   * Limit how many entries to update.
   */
  limit?: number
}

/**
 * entry upsert
 */
export type entryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * The filter to search for the entry to update in case it exists.
   */
  where: Prisma.entryWhereUniqueInput
  /**
   * In case the entry found by the `where` argument doesn't exist, create a new entry with this data.
   */
  create: Prisma.XOR<Prisma.entryCreateInput, Prisma.entryUncheckedCreateInput>
  /**
   * In case the entry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.entryUpdateInput, Prisma.entryUncheckedUpdateInput>
}

/**
 * entry delete
 */
export type entryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
  /**
   * Filter which entry to delete.
   */
  where: Prisma.entryWhereUniqueInput
}

/**
 * entry deleteMany
 */
export type entryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which entries to delete
   */
  where?: Prisma.entryWhereInput
  /**
   * Limit how many entries to delete.
   */
  limit?: number
}

/**
 * entry without action
 */
export type entryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entry
   */
  select?: Prisma.entrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the entry
   */
  omit?: Prisma.entryOmit<ExtArgs> | null
}
